import React from "react";
import Head from 'next/head';
import Link from "next/link";
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {useState} from "react";

export default function Contact() {
    const [darkMode, setDarkMode] =useState(false);
  return (
    <>
    <div className={darkMode ? "dark" : ""}>
        <Head>
          <title>Vegas Cruz Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className='text-black bg-white px-10 dark:bg-black dark:text-white'> 
          <section className="min-h-screen">
            <nav className='py-10 mb-12 flex justify-between'>
              <h1 className='text-xl font-burtons'>Developed by Vegas Cruz</h1>
              <ul className='flex items-center'>
                <li>
                  <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl'/>
                </li>
                <li><Link className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="/">Home</Link></li>
                <li><Link className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="/About">About</Link></li>
                <li><Link className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="/Contact">Contact</Link></li>
                <li><Link className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="/Resume">Resume</Link></li>
              </ul>
            </nav>
            <div className='text-center p-10'>
              <h1 className="text-6xl py-2 text-teal-600 font-medium dark:text-teal-400">Contact</h1>
              <h2 className="text-2xl py-2 text-center">Name: Vegas Cruz</h2>
              <h2 className="text-2xl py-2 text-center">Email: <a href="mailto:Vegascruz5@gmail.com">Vegascruz5@gmail.com</a></h2>
              <h2 className="text-2xl py-2 text-center">Phone Number: (608)633-4602</h2>
              <h2 className="text-2xl py-2 text-center">Mailing Address: 800a E Pearson St, Milwaukee, WI 53202</h2>
            </div>
            </section>
        </main>
        </div>
    </>
  )
}