import React from "react";
import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {useState} from "react";

export default function About() {
    const [darkMode, setDarkMode] =useState(false);
  return (
    <>
    <div className={darkMode ? "dark" : ""}>
        <Head>
          <title>Vegas Cruz Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className='text-black bg-white px-10 dark:bg-black dark:text-white'> 
          <section className="min-h-screen">
            <nav className='py-10 mb-12 flex justify-between'>
              <h1 className='text-2xl font-burtons'>Developed by Vegas Cruz</h1>
              <ul className='flex items-center'>
                <li>
                  <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl'/>
                </li>
                <li><a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="/">Home</a></li>
                <li><a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="/About">About</a></li>
                <li><a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="/Contact">Contact</a></li>
                <li><a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="/Resume">Resume</a></li>
              </ul>
            </nav>
            <div className='text-center p-10'>
              <h1 className="text-6xl py-2 text-teal-600 font-medium dark:text-teal-400">About Me!</h1>
              <h3 className="text-xl py-2">
                Hi, my name is Vegas Cruz, and I am 24 years young. I am from Sparta, WI! If you don't know where that is, it's near La Crosse. Currently, 
              I live in Milwaukee with my beautiful girlfriend, Amanda Yenter. 
              </h3>
              <h2 className="text-3xl py-2 text-teal-600 font-medium dark:text-teal-400">Interests</h2>
              <h3 className="text-xl py-2">
                My favorite hobby/passion is Volleyball. I love sand doubles, and grass triples... someday, 
                I'd like to live in California and play professionally. I also love to workout, my goal someday is a 40" vertical. Lately, I've rekindled my love for gaming. Love Call of Duty, 
                fighting games Mortal Kombat, and I also love RPG's like God of War and Dark Souls. I also love to watch TV, especially anime. Animes like Naruto, Dragonball, 
                Haikyuu, Bleach, and One Piece. 
              </h3>
              <h2 className="text-3xl py-2 text-teal-600 font-medium dark:text-teal-400">Goals</h2>
              <h3 className="text-xl py-2">
                My second goal someday is to be able to travel more... being a part time worker/student, I don't have the ability but that's a goal.
                I am currently in search for a Full-Stack or Web Developer job. I love front end, but am growing to understand/like backend more. 
                I fell in love with programming in High School where I took two programming classes. We learned C++ through Visual Studio. 
                We mostly worked on the command line, but I grew to love it the day I programmed a computer to say "Hello World". 
              </h3>
              <h2 className="text-3xl py-2 text-teal-600 font-medium dark:text-teal-400">Personality</h2>
              <h3 className="text-xl py-2">
                Let me tell you about my personality a bit. 
                I have the work ethic of a horse, EXCEPT when it comes to doing dishes haha. I'm fun, and have a very bubbly personality. I'm kind and I treat people with respect... 
                my girlfriend says I'm too much of a people pleaser, 
                but it's how I grew up.  
              </h3>
            </div>
            </section>
        </main>
        </div>
    </>
  )
}