import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Vegas Cruz Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main> 
        <section className="bg-blue-400 min-h-screen">
          <h1>Hello </h1>
        </section>
      </main>
    </>
  )
}
